# Generated by Django 2.2.4 on 2020-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clown',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Top Dan'), (2, 'Some Bob'), (3, 'Maybe Harry')]),
        ),
    ]
